### ISSUE TITLE
Problem in extending for depth messages

### ISSUE THREAD

**Issue by brahmgardner** [themichaeltsang/kinect-bridge2_catkin-indigo#1]
Hi Michael. I am having an issue adding in the client code to publish depth messages. I feel pretty confident that the depth messages are getting sent by the server. In order to capture these messages on the client side I did two things:
- Added in msg files for KinectDepthImageInfo messages and KinectDepthImage messages and updated the makefile accordingly
- Wrote a block of code in kinect_client.cpp to capture depth messages

The block I added appears as follows: 

```
 else if( coded_header.payload_id_ == KinectDepthImageMessage::ID() ){
            auto depth_msg = binary_message_coder_.decode<KinectDepthImageMessage>( coded_message );

            auto const & header = depth_msg.header_;
            auto const & payload = depth_msg.payload_;

            _KinectDepthImageMsg ros_kinect_depth_image_msg;

            for( size_t i = 0; i < payload.size(); ++ i )
            {
                _KinectDepthImageInfoMsg ros_kinect_depth_info_msg;
                ros_kinect_depth_info_msg.min_reliable_distance_ = payload[i].min_reliable_distance_;
                ros_kinect_depth_info_msg.max_reliable_distance_ = payload[i].min_reliable_distance_;
                ros_kinect_depth_image_msg.depths.emplace_back( std::move( ros_kinect_depth_info_msg ) );
            }
            kinect_speech_pub_.publish( ros_kinect_depth_image_msg );
        }
```

However, I am getting an error message that appears to connect back to the KinectDepthImageMessage::ID() line. The error is:

```
/home/brahmgarder/code/ros_catkin_my_ws/src/kinect-bridge2_catkin-indigo/src/kinect_bridge2/src/kinect_client.cpp:142:46: error: ‘template<class __ImageMessage> class KinectDepthImageMessage’ used without template parameters
         else if( coded_header.payload_id_ == KinectDepthImageMessage::ID() ){

```

I think that my issue stems from not understanding the payload_id_ value and what KinectBodiesMessage::ID() or KinectSpeechMessage::ID() do or where they come from. Any help would definitely be appreciated!!

**Comment by themichaeltsang** [comment]
Hi Brahm, 

try 
`KinectDepthImageMessage<PNGImageMessage<> >::ID()` instead
you would need to add 
`#include <messages/png_image_message.h >`

I figured this out previously by looking at kinect_server.cpp and doing pattern matching.

**Comment by brahmgardner** [comment]
Hi Michael,

The above issue appears to have been solved. However, I am now getting the following error message:

```
/home/brahmgarder/code/ros_catkin_my_ws/src/kinect-bridge2_catkin-indigo/src/kinect_bridge2/src/kinect_client.cpp:151:44: error: ‘const class BinaryMessage<>’ has no member named ‘size’
             for( size_t i = 0; i < payload.size(); ++ i )
```

I had assumed that all messages decoded by binary_message_coder_ were of the same type so I could follow the patter for the bodies and speech messages. All of my other code is identical except for the changes you suggested above.

**Comment by themichaeltsang** [comment]
Hi Brahm, 

I recommend taking a look at the pullDepthImage method in kinect_device.h to see what payload is. It looks like payload.data_ follows the form of raw data from the kinect2 sdk. The internet should have some useful information on how to process the depth images.  

Instead of doing a loop over the payload, you can do an initial check of the data sent over to see what it looks like. This should work, with the output png going into your .ros folder:

```
std::ofstream output_stream( "test_kinect_depth.png", std::ios::binary );
depth_msg.packAs<PNGImageMessage<>>(output_stream);
output_stream.close();

```

**Comment by brahmgardner** [comment]
Hi Michael,

I ended up converting payload.data_ to a cv::Mat and then using cvbridge to publish the matrix as a sensor_msgs/Image message, and this worked nicely. Thank you for your help, and I will definitely let you know if I have any more questions.
